server {
	listen 127.0.0.1:8080;
	listen 127.0.0.2:8080;
	listen 8085;
	listen 8087;
	server_name example.com;
    root ./website;
    index index.html;
    client_max_body_size 10000000;

	error_page 400 ./website/errors/400.html;
	error_page 403 ./website/errors/403.html;
    error_page 404 ./website/errors/404.html;
	error_page 405 ./website/errors/405.html;
	error_page 413 ./website/errors/413.html;
    error_page 500 ./website/errors/500.html;
	error_page 501 ./website/errors/501.html;
	error_page 504 ./website/errors/504.html;
	error_page 505 ./website/errors/505.html;

    location /uploads {
        root ./website/uploads;
        allow_methods GET POST DELETE;
        autoindex on;
		redirect POST /index.html 303;
    }

    location /cgi-bin {
        root ./cgi-bin;
		cgi_extension .py .php;
        cgi_interpreter .py /usr/bin/python3;
		cgi_interpreter .php /usr/bin/php-cgi;
        allow_methods POST GET;
        autoindex off;
    }
}

server1 {
    listen 0.0.0.0:8081;
    root ./website;
    client_max_body_size 1000000;

	error_page 400 ./website/errors/400.html;
	error_page 403 ./website/errors/403.html;
    error_page 404 ./website/errors/404.html;
	error_page 405 ./website/errors/405.html;
	error_page 413 ./website/errors/413.html;
    error_page 500 ./website/errors/500.html;
	error_page 501 ./website/errors/501.html;
	error_page 504 ./website/errors/504.html;
	error_page 505 ./website/errors/505.html;

    location /uploads {
        root ./website/uploads;
        allow_methods GET  POST; 
        autoindex on;
    }

	location /cgi-bin {
        root ./cgi-bin;
		cgi_extension .py .php;
        cgi_interpreter .py /usr/bin/python3;
		cgi_interpreter .php /usr/bin/php-cgi;
        allow_methods POST GET;
        autoindex off;
    }

}

server2 {
    listen 8082;
	server_name example.com;
    root ./website;
    index index.html;
    client_max_body_size 1000000;

	error_page 400 ./website/errors/400.html;
	error_page 403 ./website/errors/403.html;
    error_page 404 ./website/errors/404.html;
	error_page 405 ./website/errors/405.html;
	error_page 413 ./website/errors/413.html;
    error_page 500 ./website/errors/500.html;
	error_page 501 ./website/errors/501.html;
	error_page 504 ./website/errors/504.html;
	error_page 505 ./website/errors/505.html;

    location /cgi-bin {
        root ./cgi-bin;
        cgi_extension .py .php;
        cgi_interpreter .py /usr/bin/python3;
		cgi_interpreter .php /usr/bin/php-cgi;
        allow_methods POST GET;
        autoindex off;
    }

	location /uploads {
        root ./website/uploads;
        allow_methods GET POST DELETE;
        autoindex on;
    }

}


