server {
    listen 8080;
	server_name example.com;
    root   ;
    index index.html;
    client_max_body_size 1000000;

    error_page 404 ./website/errors/404.html;
	error_page 405 ./website/errors/405.html;
    error_page 500 ./website/errors/500.html;

    location /uploads {
        root ./uploads;
        allow_methods GET POST DELETE;
        autoindex on;
    }

    location /cgi-bin {
        root ./cgi-bin;
		cgi_extension .py .php;
        cgi_interpreter .py /usr/bin/python3;
		cgi_interpreter .php /usr/bin/php-cgi;
        allow_methods POST GET;
        autoindex off;
    }
}