# Server-weite Direktiven
listen 8080;
root ./www;
index index.html;
client_max_body_size 1000000;

# Fehlerseiten
error_page 404 ./errors/404.html;
error_page 500 ./errors/500.html;

# Location für Uploads
location /uploads {
    root ./www/uploads;
    allow_methods POST GET;
    autoindex on;
}

# Location für CGI
location /cgi-bin {
    root ./www/cgi-bin;
    cgi_extension .py;
    allow_methods GET POST;
    autoindex off;
}
